import { SpriteProps } from './@core/Sprite';

const spriteData: { [index: string]: SpriteProps } = {
    ui: {
        src: './assets/ui.png',
        sheet: {
            'self-select': [
                [4, 0],
                [5, 0],
            ],
            select: [[4, 0]],
            dot: [[1, 0]],
            solid: [[0, 1]],
        },
    },
    player: {
        src: './assets/player.png',
        frameWidth: 20,
        frameHeight: 20,
        frameTime: 300,
        sheet: {
            default: [[0, 2]],
            walk: [
                [1, 2],
                [2, 2],
            ],
            action: [
                [0, 1],
                [2, 1],
            ],
        },
    },
    objects: {
        src: './assets/objects.png',
        frameWidth: 32,
        frameHeight: 32,
        sheet: {
            floor: [[0, 0]],
            wall: [[0, 3]],
            wallBorderTop: [[3, 3]],
            wallVerticalTopRight: [[1, 3]],
            wallVerticalTopLeft: [[2, 3]],
            wallVerticalBottomRight: [[6, 3]],
            wallVerticalBottomLeft: [[7, 3]],
            wallVerticalRight: [[4, 3]],
            wallVerticalLeft: [[5, 3]],
            wallCornerRight: [[8, 3]],
            wallCornerLeft: [[9, 3]],
            cart: [[3, 0]],
            gateLeftOff: [[4, 0]],
            gateRightOff: [[5, 0]],
            gateLeftOn: [[6, 0]],
            gateRightOn: [[7, 0]],
            containerFrozenFood1: [[0, 4]],
            containerFrozenFood2: [[0, 5]],
            shelfFrozenFood:[[1, 5]],
            mop: [[8, 0]],
            shelfEmpty: [[2, 5]],
            shelfHorizontal1: [[3, 5]],
            shelfHorizontal2: [[4, 5]],
            shelfVertical11: [[15, 4]],
            shelfVertical12: [[15, 3]],
            shelfVertical13: [[15, 2]],
            shelfVertical21: [[16, 4]],
            shelfVertical22: [[16, 3]],
            shelfVertical23: [[16, 2]],
            shelfVertical31: [[13, 4]],
            shelfVertical32: [[13, 3]],
            shelfVertical33: [[13, 2]],
            crate1: [[5, 5]],
            crate2: [[6, 5]],
            crate3: [[7, 5]],
            crate4: [[8, 5]],
            fish1: [[9, 5]],
            fish2: [[10, 5]],
            fish3: [[11, 5]],
            fish4: [[12, 5]],
            meat1: [[13, 5]],
            meat2: [[14, 5]],
            meat3: [[15, 5]],
            scale: [[16, 5]],
            electric: [[1, 4]],
            cake: [[2, 4]],
            boxes: [[3, 4]],
            baskets: [[4, 4]],
            bread: [[5, 4]],
            cartValidationFloor: [[1, 0]],
        },
    },
    footstep: {
        src: './assets/footstep.png',
        sheet: {
            default: [
                [0, 0],
                [2, 0],
            ],
        },
        opacity: 0.75,
        frameTime: 150,
    },
};

export default spriteData;
